export default {
    palette: {
        primary: {
            light: "#af8406",
            main: "#fabd09",
            dark: "#fbca3a",
            contrastText: "#242424",
            background: "rgba(255,147,44,.6)",
        },
        secondary: {
            light: "#191919",
            main: "#242424",
            dark: "#4f4f4f",
            contrastText: "#fff",
        },
        tertiary: {
            light: "#596c60",
            main: "#809b8a",
            dark: "#99afa1",
            contrastText: "#000",
        },
        white: {
            light: "#af8406",
            main: "#ffffff",
            dark: "#fbca3a",
            contrastText: "#fff",
        },
        dark: {
            light: "#191919",
            main: "#242424",
            dark: "#000000",
            contrastText: "#fff",
        },
    },
    typography: {
        // htmlFontSize: 14,
        fontFamily: ["Courier Prime"],
        h1: {
            fontFamily: "Courier Prime",
            fontSize: "2.25rem",
            fontWeight: 400,
            color: "#242424",
            lineHeight: "2",
        },
        h2: {
            fontFamily: "Courier Prime",
            fontSize: "1.5rem",
            fontWeight: 400,
            color: "#242424",
            lineHeight: "1.5",
        },
        h3: {
            fontFamily: "Courier Prime",
            fontSize: "1.25rem",
            fontWeight: 400,
            color: "#242424",
            lineHeight: "1.5",
        },
        h4: {
            fontFamily: "Courier Prime",
            fontSize: "1.25rem",
            fontWeight: 400,
            color: "#242424",
            lineHeight: "1.5",
        },
        h5: {
            fontFamily: "Courier Prime",
            fontSize: "1.25rem",
            fontWeight: 400,
            color: "#242424",
            lineHeight: "1.6",
        },
        h6: {
            fontFamily: "Courier Prime",
            fontSize: "1.25rem",
            fontWeight: 400,
            color: "#242424",
            lineHeight: "1.6",
        },
        body1: {
            fontFamily: "Courier Prime",
            fontSize: "1rem",
            fontWeight: 400,
            color: "#242424",
            lineHeight: "1.6",
        },
        body2: {
            fontFamily: "tahoma",
            fontSize: "1rem",
            fontWeight: 400,
            color: "#242424",
            lineHeight: "1.6",
        },
    },
    shape: {
        borderRadius: 3,
    },
};
